'use strict'

/*
 logo in file ./static/txt/logo.txt is generated by
  http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Calvin%20S&t=%20P%20A%20G%20E%0A
*/ 

const { AsyncObject } = require('@cuties/cutie');

class PrintedToConsolePageLogo extends AsyncObject {

  constructor(logo, version) {
    super(logo, version);
  }

  definedSyncCall() {
    return (logo, version) => {
      console.log(`${logo}${version}\n`);
      return logo;
    }
  }

}

module.exports = PrintedToConsolePageLogo;
